// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rollout-cache.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_rollout_2dcache_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_rollout_2dcache_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_rollout_2dcache_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_rollout_2dcache_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_rollout_2dcache_2eproto;
namespace specrl {
class TokenList;
class TokenListDefaultTypeInternal;
extern TokenListDefaultTypeInternal _TokenList_default_instance_;
class UpdateCacheRequest;
class UpdateCacheRequestDefaultTypeInternal;
extern UpdateCacheRequestDefaultTypeInternal _UpdateCacheRequest_default_instance_;
class UpdateCacheResponse;
class UpdateCacheResponseDefaultTypeInternal;
extern UpdateCacheResponseDefaultTypeInternal _UpdateCacheResponse_default_instance_;
}  // namespace specrl
PROTOBUF_NAMESPACE_OPEN
template<> ::specrl::TokenList* Arena::CreateMaybeMessage<::specrl::TokenList>(Arena*);
template<> ::specrl::UpdateCacheRequest* Arena::CreateMaybeMessage<::specrl::UpdateCacheRequest>(Arena*);
template<> ::specrl::UpdateCacheResponse* Arena::CreateMaybeMessage<::specrl::UpdateCacheResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace specrl {

// ===================================================================

class UpdateCacheRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:specrl.UpdateCacheRequest) */ {
 public:
  inline UpdateCacheRequest() : UpdateCacheRequest(nullptr) {};
  virtual ~UpdateCacheRequest();

  UpdateCacheRequest(const UpdateCacheRequest& from);
  UpdateCacheRequest(UpdateCacheRequest&& from) noexcept
    : UpdateCacheRequest() {
    *this = ::std::move(from);
  }

  inline UpdateCacheRequest& operator=(const UpdateCacheRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateCacheRequest& operator=(UpdateCacheRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UpdateCacheRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UpdateCacheRequest* internal_default_instance() {
    return reinterpret_cast<const UpdateCacheRequest*>(
               &_UpdateCacheRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UpdateCacheRequest& a, UpdateCacheRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(UpdateCacheRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpdateCacheRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UpdateCacheRequest* New() const final {
    return CreateMaybeMessage<UpdateCacheRequest>(nullptr);
  }

  UpdateCacheRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UpdateCacheRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UpdateCacheRequest& from);
  void MergeFrom(const UpdateCacheRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UpdateCacheRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "specrl.UpdateCacheRequest";
  }
  protected:
  explicit UpdateCacheRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_rollout_2dcache_2eproto);
    return ::descriptor_table_rollout_2dcache_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResponsesFieldNumber = 3,
    kPromptFieldNumber = 2,
    kPromptHashFieldNumber = 1,
  };
  // repeated .specrl.TokenList responses = 3;
  int responses_size() const;
  private:
  int _internal_responses_size() const;
  public:
  void clear_responses();
  ::specrl::TokenList* mutable_responses(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::specrl::TokenList >*
      mutable_responses();
  private:
  const ::specrl::TokenList& _internal_responses(int index) const;
  ::specrl::TokenList* _internal_add_responses();
  public:
  const ::specrl::TokenList& responses(int index) const;
  ::specrl::TokenList* add_responses();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::specrl::TokenList >&
      responses() const;

  // .specrl.TokenList prompt = 2;
  bool has_prompt() const;
  private:
  bool _internal_has_prompt() const;
  public:
  void clear_prompt();
  const ::specrl::TokenList& prompt() const;
  ::specrl::TokenList* release_prompt();
  ::specrl::TokenList* mutable_prompt();
  void set_allocated_prompt(::specrl::TokenList* prompt);
  private:
  const ::specrl::TokenList& _internal_prompt() const;
  ::specrl::TokenList* _internal_mutable_prompt();
  public:
  void unsafe_arena_set_allocated_prompt(
      ::specrl::TokenList* prompt);
  ::specrl::TokenList* unsafe_arena_release_prompt();

  // uint64 prompt_hash = 1;
  void clear_prompt_hash();
  ::PROTOBUF_NAMESPACE_ID::uint64 prompt_hash() const;
  void set_prompt_hash(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_prompt_hash() const;
  void _internal_set_prompt_hash(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:specrl.UpdateCacheRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::specrl::TokenList > responses_;
  ::specrl::TokenList* prompt_;
  ::PROTOBUF_NAMESPACE_ID::uint64 prompt_hash_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_rollout_2dcache_2eproto;
};
// -------------------------------------------------------------------

class TokenList PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:specrl.TokenList) */ {
 public:
  inline TokenList() : TokenList(nullptr) {};
  virtual ~TokenList();

  TokenList(const TokenList& from);
  TokenList(TokenList&& from) noexcept
    : TokenList() {
    *this = ::std::move(from);
  }

  inline TokenList& operator=(const TokenList& from) {
    CopyFrom(from);
    return *this;
  }
  inline TokenList& operator=(TokenList&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TokenList& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TokenList* internal_default_instance() {
    return reinterpret_cast<const TokenList*>(
               &_TokenList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(TokenList& a, TokenList& b) {
    a.Swap(&b);
  }
  inline void Swap(TokenList* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TokenList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TokenList* New() const final {
    return CreateMaybeMessage<TokenList>(nullptr);
  }

  TokenList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TokenList>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TokenList& from);
  void MergeFrom(const TokenList& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TokenList* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "specrl.TokenList";
  }
  protected:
  explicit TokenList(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_rollout_2dcache_2eproto);
    return ::descriptor_table_rollout_2dcache_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTokensFieldNumber = 1,
  };
  // repeated int32 tokens = 1;
  int tokens_size() const;
  private:
  int _internal_tokens_size() const;
  public:
  void clear_tokens();
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_tokens(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      _internal_tokens() const;
  void _internal_add_tokens(::PROTOBUF_NAMESPACE_ID::int32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      _internal_mutable_tokens();
  public:
  ::PROTOBUF_NAMESPACE_ID::int32 tokens(int index) const;
  void set_tokens(int index, ::PROTOBUF_NAMESPACE_ID::int32 value);
  void add_tokens(::PROTOBUF_NAMESPACE_ID::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      tokens() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_tokens();

  // @@protoc_insertion_point(class_scope:specrl.TokenList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 > tokens_;
  mutable std::atomic<int> _tokens_cached_byte_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_rollout_2dcache_2eproto;
};
// -------------------------------------------------------------------

class UpdateCacheResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:specrl.UpdateCacheResponse) */ {
 public:
  inline UpdateCacheResponse() : UpdateCacheResponse(nullptr) {};
  virtual ~UpdateCacheResponse();

  UpdateCacheResponse(const UpdateCacheResponse& from);
  UpdateCacheResponse(UpdateCacheResponse&& from) noexcept
    : UpdateCacheResponse() {
    *this = ::std::move(from);
  }

  inline UpdateCacheResponse& operator=(const UpdateCacheResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateCacheResponse& operator=(UpdateCacheResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UpdateCacheResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UpdateCacheResponse* internal_default_instance() {
    return reinterpret_cast<const UpdateCacheResponse*>(
               &_UpdateCacheResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(UpdateCacheResponse& a, UpdateCacheResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(UpdateCacheResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpdateCacheResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UpdateCacheResponse* New() const final {
    return CreateMaybeMessage<UpdateCacheResponse>(nullptr);
  }

  UpdateCacheResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UpdateCacheResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UpdateCacheResponse& from);
  void MergeFrom(const UpdateCacheResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UpdateCacheResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "specrl.UpdateCacheResponse";
  }
  protected:
  explicit UpdateCacheResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_rollout_2dcache_2eproto);
    return ::descriptor_table_rollout_2dcache_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:specrl.UpdateCacheResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_rollout_2dcache_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UpdateCacheRequest

// uint64 prompt_hash = 1;
inline void UpdateCacheRequest::clear_prompt_hash() {
  prompt_hash_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 UpdateCacheRequest::_internal_prompt_hash() const {
  return prompt_hash_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 UpdateCacheRequest::prompt_hash() const {
  // @@protoc_insertion_point(field_get:specrl.UpdateCacheRequest.prompt_hash)
  return _internal_prompt_hash();
}
inline void UpdateCacheRequest::_internal_set_prompt_hash(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  prompt_hash_ = value;
}
inline void UpdateCacheRequest::set_prompt_hash(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_prompt_hash(value);
  // @@protoc_insertion_point(field_set:specrl.UpdateCacheRequest.prompt_hash)
}

// .specrl.TokenList prompt = 2;
inline bool UpdateCacheRequest::_internal_has_prompt() const {
  return this != internal_default_instance() && prompt_ != nullptr;
}
inline bool UpdateCacheRequest::has_prompt() const {
  return _internal_has_prompt();
}
inline void UpdateCacheRequest::clear_prompt() {
  if (GetArena() == nullptr && prompt_ != nullptr) {
    delete prompt_;
  }
  prompt_ = nullptr;
}
inline const ::specrl::TokenList& UpdateCacheRequest::_internal_prompt() const {
  const ::specrl::TokenList* p = prompt_;
  return p != nullptr ? *p : *reinterpret_cast<const ::specrl::TokenList*>(
      &::specrl::_TokenList_default_instance_);
}
inline const ::specrl::TokenList& UpdateCacheRequest::prompt() const {
  // @@protoc_insertion_point(field_get:specrl.UpdateCacheRequest.prompt)
  return _internal_prompt();
}
inline void UpdateCacheRequest::unsafe_arena_set_allocated_prompt(
    ::specrl::TokenList* prompt) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(prompt_);
  }
  prompt_ = prompt;
  if (prompt) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:specrl.UpdateCacheRequest.prompt)
}
inline ::specrl::TokenList* UpdateCacheRequest::release_prompt() {
  auto temp = unsafe_arena_release_prompt();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::specrl::TokenList* UpdateCacheRequest::unsafe_arena_release_prompt() {
  // @@protoc_insertion_point(field_release:specrl.UpdateCacheRequest.prompt)
  
  ::specrl::TokenList* temp = prompt_;
  prompt_ = nullptr;
  return temp;
}
inline ::specrl::TokenList* UpdateCacheRequest::_internal_mutable_prompt() {
  
  if (prompt_ == nullptr) {
    auto* p = CreateMaybeMessage<::specrl::TokenList>(GetArena());
    prompt_ = p;
  }
  return prompt_;
}
inline ::specrl::TokenList* UpdateCacheRequest::mutable_prompt() {
  // @@protoc_insertion_point(field_mutable:specrl.UpdateCacheRequest.prompt)
  return _internal_mutable_prompt();
}
inline void UpdateCacheRequest::set_allocated_prompt(::specrl::TokenList* prompt) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete prompt_;
  }
  if (prompt) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(prompt);
    if (message_arena != submessage_arena) {
      prompt = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, prompt, submessage_arena);
    }
    
  } else {
    
  }
  prompt_ = prompt;
  // @@protoc_insertion_point(field_set_allocated:specrl.UpdateCacheRequest.prompt)
}

// repeated .specrl.TokenList responses = 3;
inline int UpdateCacheRequest::_internal_responses_size() const {
  return responses_.size();
}
inline int UpdateCacheRequest::responses_size() const {
  return _internal_responses_size();
}
inline void UpdateCacheRequest::clear_responses() {
  responses_.Clear();
}
inline ::specrl::TokenList* UpdateCacheRequest::mutable_responses(int index) {
  // @@protoc_insertion_point(field_mutable:specrl.UpdateCacheRequest.responses)
  return responses_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::specrl::TokenList >*
UpdateCacheRequest::mutable_responses() {
  // @@protoc_insertion_point(field_mutable_list:specrl.UpdateCacheRequest.responses)
  return &responses_;
}
inline const ::specrl::TokenList& UpdateCacheRequest::_internal_responses(int index) const {
  return responses_.Get(index);
}
inline const ::specrl::TokenList& UpdateCacheRequest::responses(int index) const {
  // @@protoc_insertion_point(field_get:specrl.UpdateCacheRequest.responses)
  return _internal_responses(index);
}
inline ::specrl::TokenList* UpdateCacheRequest::_internal_add_responses() {
  return responses_.Add();
}
inline ::specrl::TokenList* UpdateCacheRequest::add_responses() {
  // @@protoc_insertion_point(field_add:specrl.UpdateCacheRequest.responses)
  return _internal_add_responses();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::specrl::TokenList >&
UpdateCacheRequest::responses() const {
  // @@protoc_insertion_point(field_list:specrl.UpdateCacheRequest.responses)
  return responses_;
}

// -------------------------------------------------------------------

// TokenList

// repeated int32 tokens = 1;
inline int TokenList::_internal_tokens_size() const {
  return tokens_.size();
}
inline int TokenList::tokens_size() const {
  return _internal_tokens_size();
}
inline void TokenList::clear_tokens() {
  tokens_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TokenList::_internal_tokens(int index) const {
  return tokens_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TokenList::tokens(int index) const {
  // @@protoc_insertion_point(field_get:specrl.TokenList.tokens)
  return _internal_tokens(index);
}
inline void TokenList::set_tokens(int index, ::PROTOBUF_NAMESPACE_ID::int32 value) {
  tokens_.Set(index, value);
  // @@protoc_insertion_point(field_set:specrl.TokenList.tokens)
}
inline void TokenList::_internal_add_tokens(::PROTOBUF_NAMESPACE_ID::int32 value) {
  tokens_.Add(value);
}
inline void TokenList::add_tokens(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_add_tokens(value);
  // @@protoc_insertion_point(field_add:specrl.TokenList.tokens)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
TokenList::_internal_tokens() const {
  return tokens_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
TokenList::tokens() const {
  // @@protoc_insertion_point(field_list:specrl.TokenList.tokens)
  return _internal_tokens();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
TokenList::_internal_mutable_tokens() {
  return &tokens_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
TokenList::mutable_tokens() {
  // @@protoc_insertion_point(field_mutable_list:specrl.TokenList.tokens)
  return _internal_mutable_tokens();
}

// -------------------------------------------------------------------

// UpdateCacheResponse

// bool success = 1;
inline void UpdateCacheResponse::clear_success() {
  success_ = false;
}
inline bool UpdateCacheResponse::_internal_success() const {
  return success_;
}
inline bool UpdateCacheResponse::success() const {
  // @@protoc_insertion_point(field_get:specrl.UpdateCacheResponse.success)
  return _internal_success();
}
inline void UpdateCacheResponse::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void UpdateCacheResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:specrl.UpdateCacheResponse.success)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace specrl

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_rollout_2dcache_2eproto
