// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rollout-cache.proto

#include "rollout-cache.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_rollout_2dcache_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_TokenList_rollout_2dcache_2eproto;
namespace specrl {
class UpdateCacheRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<UpdateCacheRequest> _instance;
} _UpdateCacheRequest_default_instance_;
class TokenListDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<TokenList> _instance;
} _TokenList_default_instance_;
class UpdateCacheResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<UpdateCacheResponse> _instance;
} _UpdateCacheResponse_default_instance_;
}  // namespace specrl
static void InitDefaultsscc_info_TokenList_rollout_2dcache_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::specrl::_TokenList_default_instance_;
    new (ptr) ::specrl::TokenList();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::specrl::TokenList::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_TokenList_rollout_2dcache_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_TokenList_rollout_2dcache_2eproto}, {}};

static void InitDefaultsscc_info_UpdateCacheRequest_rollout_2dcache_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::specrl::_UpdateCacheRequest_default_instance_;
    new (ptr) ::specrl::UpdateCacheRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::specrl::UpdateCacheRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_UpdateCacheRequest_rollout_2dcache_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_UpdateCacheRequest_rollout_2dcache_2eproto}, {
      &scc_info_TokenList_rollout_2dcache_2eproto.base,}};

static void InitDefaultsscc_info_UpdateCacheResponse_rollout_2dcache_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::specrl::_UpdateCacheResponse_default_instance_;
    new (ptr) ::specrl::UpdateCacheResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::specrl::UpdateCacheResponse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_UpdateCacheResponse_rollout_2dcache_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_UpdateCacheResponse_rollout_2dcache_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_rollout_2dcache_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_rollout_2dcache_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_rollout_2dcache_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_rollout_2dcache_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::specrl::UpdateCacheRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::specrl::UpdateCacheRequest, prompt_hash_),
  PROTOBUF_FIELD_OFFSET(::specrl::UpdateCacheRequest, prompt_),
  PROTOBUF_FIELD_OFFSET(::specrl::UpdateCacheRequest, responses_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::specrl::TokenList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::specrl::TokenList, tokens_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::specrl::UpdateCacheResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::specrl::UpdateCacheResponse, success_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::specrl::UpdateCacheRequest)},
  { 8, -1, sizeof(::specrl::TokenList)},
  { 14, -1, sizeof(::specrl::UpdateCacheResponse)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::specrl::_UpdateCacheRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::specrl::_TokenList_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::specrl::_UpdateCacheResponse_default_instance_),
};

const char descriptor_table_protodef_rollout_2dcache_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023rollout-cache.proto\022\006specrl\"r\n\022UpdateC"
  "acheRequest\022\023\n\013prompt_hash\030\001 \001(\004\022!\n\006prom"
  "pt\030\002 \001(\0132\021.specrl.TokenList\022$\n\tresponses"
  "\030\003 \003(\0132\021.specrl.TokenList\"\033\n\tTokenList\022\016"
  "\n\006tokens\030\001 \003(\005\"&\n\023UpdateCacheResponse\022\017\n"
  "\007success\030\001 \001(\0102_\n\023RolloutCacheService\022H\n"
  "\013UpdateCache\022\032.specrl.UpdateCacheRequest"
  "\032\033.specrl.UpdateCacheResponse\"\000b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_rollout_2dcache_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_rollout_2dcache_2eproto_sccs[3] = {
  &scc_info_TokenList_rollout_2dcache_2eproto.base,
  &scc_info_UpdateCacheRequest_rollout_2dcache_2eproto.base,
  &scc_info_UpdateCacheResponse_rollout_2dcache_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_rollout_2dcache_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_rollout_2dcache_2eproto = {
  false, false, descriptor_table_protodef_rollout_2dcache_2eproto, "rollout-cache.proto", 319,
  &descriptor_table_rollout_2dcache_2eproto_once, descriptor_table_rollout_2dcache_2eproto_sccs, descriptor_table_rollout_2dcache_2eproto_deps, 3, 0,
  schemas, file_default_instances, TableStruct_rollout_2dcache_2eproto::offsets,
  file_level_metadata_rollout_2dcache_2eproto, 3, file_level_enum_descriptors_rollout_2dcache_2eproto, file_level_service_descriptors_rollout_2dcache_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_rollout_2dcache_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_rollout_2dcache_2eproto)), true);
namespace specrl {

// ===================================================================

void UpdateCacheRequest::InitAsDefaultInstance() {
  ::specrl::_UpdateCacheRequest_default_instance_._instance.get_mutable()->prompt_ = const_cast< ::specrl::TokenList*>(
      ::specrl::TokenList::internal_default_instance());
}
class UpdateCacheRequest::_Internal {
 public:
  static const ::specrl::TokenList& prompt(const UpdateCacheRequest* msg);
};

const ::specrl::TokenList&
UpdateCacheRequest::_Internal::prompt(const UpdateCacheRequest* msg) {
  return *msg->prompt_;
}
UpdateCacheRequest::UpdateCacheRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  responses_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:specrl.UpdateCacheRequest)
}
UpdateCacheRequest::UpdateCacheRequest(const UpdateCacheRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      responses_(from.responses_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_prompt()) {
    prompt_ = new ::specrl::TokenList(*from.prompt_);
  } else {
    prompt_ = nullptr;
  }
  prompt_hash_ = from.prompt_hash_;
  // @@protoc_insertion_point(copy_constructor:specrl.UpdateCacheRequest)
}

void UpdateCacheRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_UpdateCacheRequest_rollout_2dcache_2eproto.base);
  ::memset(&prompt_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&prompt_hash_) -
      reinterpret_cast<char*>(&prompt_)) + sizeof(prompt_hash_));
}

UpdateCacheRequest::~UpdateCacheRequest() {
  // @@protoc_insertion_point(destructor:specrl.UpdateCacheRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void UpdateCacheRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete prompt_;
}

void UpdateCacheRequest::ArenaDtor(void* object) {
  UpdateCacheRequest* _this = reinterpret_cast< UpdateCacheRequest* >(object);
  (void)_this;
}
void UpdateCacheRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void UpdateCacheRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const UpdateCacheRequest& UpdateCacheRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_UpdateCacheRequest_rollout_2dcache_2eproto.base);
  return *internal_default_instance();
}


void UpdateCacheRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:specrl.UpdateCacheRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  responses_.Clear();
  if (GetArena() == nullptr && prompt_ != nullptr) {
    delete prompt_;
  }
  prompt_ = nullptr;
  prompt_hash_ = PROTOBUF_ULONGLONG(0);
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UpdateCacheRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint64 prompt_hash = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          prompt_hash_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .specrl.TokenList prompt = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_prompt(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .specrl.TokenList responses = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_responses(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* UpdateCacheRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:specrl.UpdateCacheRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 prompt_hash = 1;
  if (this->prompt_hash() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->_internal_prompt_hash(), target);
  }

  // .specrl.TokenList prompt = 2;
  if (this->has_prompt()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::prompt(this), target, stream);
  }

  // repeated .specrl.TokenList responses = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_responses_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, this->_internal_responses(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:specrl.UpdateCacheRequest)
  return target;
}

size_t UpdateCacheRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:specrl.UpdateCacheRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .specrl.TokenList responses = 3;
  total_size += 1UL * this->_internal_responses_size();
  for (const auto& msg : this->responses_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .specrl.TokenList prompt = 2;
  if (this->has_prompt()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *prompt_);
  }

  // uint64 prompt_hash = 1;
  if (this->prompt_hash() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_prompt_hash());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UpdateCacheRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:specrl.UpdateCacheRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const UpdateCacheRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<UpdateCacheRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:specrl.UpdateCacheRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:specrl.UpdateCacheRequest)
    MergeFrom(*source);
  }
}

void UpdateCacheRequest::MergeFrom(const UpdateCacheRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:specrl.UpdateCacheRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  responses_.MergeFrom(from.responses_);
  if (from.has_prompt()) {
    _internal_mutable_prompt()->::specrl::TokenList::MergeFrom(from._internal_prompt());
  }
  if (from.prompt_hash() != 0) {
    _internal_set_prompt_hash(from._internal_prompt_hash());
  }
}

void UpdateCacheRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:specrl.UpdateCacheRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UpdateCacheRequest::CopyFrom(const UpdateCacheRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:specrl.UpdateCacheRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdateCacheRequest::IsInitialized() const {
  return true;
}

void UpdateCacheRequest::InternalSwap(UpdateCacheRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  responses_.InternalSwap(&other->responses_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UpdateCacheRequest, prompt_hash_)
      + sizeof(UpdateCacheRequest::prompt_hash_)
      - PROTOBUF_FIELD_OFFSET(UpdateCacheRequest, prompt_)>(
          reinterpret_cast<char*>(&prompt_),
          reinterpret_cast<char*>(&other->prompt_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UpdateCacheRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void TokenList::InitAsDefaultInstance() {
}
class TokenList::_Internal {
 public:
};

TokenList::TokenList(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  tokens_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:specrl.TokenList)
}
TokenList::TokenList(const TokenList& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      tokens_(from.tokens_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:specrl.TokenList)
}

void TokenList::SharedCtor() {
}

TokenList::~TokenList() {
  // @@protoc_insertion_point(destructor:specrl.TokenList)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void TokenList::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void TokenList::ArenaDtor(void* object) {
  TokenList* _this = reinterpret_cast< TokenList* >(object);
  (void)_this;
}
void TokenList::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TokenList::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TokenList& TokenList::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_TokenList_rollout_2dcache_2eproto.base);
  return *internal_default_instance();
}


void TokenList::Clear() {
// @@protoc_insertion_point(message_clear_start:specrl.TokenList)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  tokens_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TokenList::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated int32 tokens = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_tokens(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8) {
          _internal_add_tokens(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* TokenList::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:specrl.TokenList)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 tokens = 1;
  {
    int byte_size = _tokens_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          1, _internal_tokens(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:specrl.TokenList)
  return target;
}

size_t TokenList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:specrl.TokenList)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 tokens = 1;
  {
    size_t data_size = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      Int32Size(this->tokens_);
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _tokens_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TokenList::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:specrl.TokenList)
  GOOGLE_DCHECK_NE(&from, this);
  const TokenList* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<TokenList>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:specrl.TokenList)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:specrl.TokenList)
    MergeFrom(*source);
  }
}

void TokenList::MergeFrom(const TokenList& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:specrl.TokenList)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  tokens_.MergeFrom(from.tokens_);
}

void TokenList::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:specrl.TokenList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TokenList::CopyFrom(const TokenList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:specrl.TokenList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TokenList::IsInitialized() const {
  return true;
}

void TokenList::InternalSwap(TokenList* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  tokens_.InternalSwap(&other->tokens_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TokenList::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void UpdateCacheResponse::InitAsDefaultInstance() {
}
class UpdateCacheResponse::_Internal {
 public:
};

UpdateCacheResponse::UpdateCacheResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:specrl.UpdateCacheResponse)
}
UpdateCacheResponse::UpdateCacheResponse(const UpdateCacheResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  success_ = from.success_;
  // @@protoc_insertion_point(copy_constructor:specrl.UpdateCacheResponse)
}

void UpdateCacheResponse::SharedCtor() {
  success_ = false;
}

UpdateCacheResponse::~UpdateCacheResponse() {
  // @@protoc_insertion_point(destructor:specrl.UpdateCacheResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void UpdateCacheResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void UpdateCacheResponse::ArenaDtor(void* object) {
  UpdateCacheResponse* _this = reinterpret_cast< UpdateCacheResponse* >(object);
  (void)_this;
}
void UpdateCacheResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void UpdateCacheResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const UpdateCacheResponse& UpdateCacheResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_UpdateCacheResponse_rollout_2dcache_2eproto.base);
  return *internal_default_instance();
}


void UpdateCacheResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:specrl.UpdateCacheResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  success_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UpdateCacheResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* UpdateCacheResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:specrl.UpdateCacheResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:specrl.UpdateCacheResponse)
  return target;
}

size_t UpdateCacheResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:specrl.UpdateCacheResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool success = 1;
  if (this->success() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UpdateCacheResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:specrl.UpdateCacheResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const UpdateCacheResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<UpdateCacheResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:specrl.UpdateCacheResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:specrl.UpdateCacheResponse)
    MergeFrom(*source);
  }
}

void UpdateCacheResponse::MergeFrom(const UpdateCacheResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:specrl.UpdateCacheResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.success() != 0) {
    _internal_set_success(from._internal_success());
  }
}

void UpdateCacheResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:specrl.UpdateCacheResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UpdateCacheResponse::CopyFrom(const UpdateCacheResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:specrl.UpdateCacheResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdateCacheResponse::IsInitialized() const {
  return true;
}

void UpdateCacheResponse::InternalSwap(UpdateCacheResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(success_, other->success_);
}

::PROTOBUF_NAMESPACE_ID::Metadata UpdateCacheResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace specrl
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::specrl::UpdateCacheRequest* Arena::CreateMaybeMessage< ::specrl::UpdateCacheRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::specrl::UpdateCacheRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::specrl::TokenList* Arena::CreateMaybeMessage< ::specrl::TokenList >(Arena* arena) {
  return Arena::CreateMessageInternal< ::specrl::TokenList >(arena);
}
template<> PROTOBUF_NOINLINE ::specrl::UpdateCacheResponse* Arena::CreateMaybeMessage< ::specrl::UpdateCacheResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::specrl::UpdateCacheResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
