// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rollout-cache.proto

#include "rollout-cache.pb.h"
#include "rollout-cache.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace specrl {

static const char* RolloutCacheService_method_names[] = {
  "/specrl.RolloutCacheService/UpdateCache",
};

std::unique_ptr< RolloutCacheService::Stub> RolloutCacheService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RolloutCacheService::Stub> stub(new RolloutCacheService::Stub(channel));
  return stub;
}

RolloutCacheService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_UpdateCache_(RolloutCacheService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RolloutCacheService::Stub::UpdateCache(::grpc::ClientContext* context, const ::specrl::UpdateCacheRequest& request, ::specrl::UpdateCacheResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_UpdateCache_, context, request, response);
}

void RolloutCacheService::Stub::experimental_async::UpdateCache(::grpc::ClientContext* context, const ::specrl::UpdateCacheRequest* request, ::specrl::UpdateCacheResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UpdateCache_, context, request, response, std::move(f));
}

void RolloutCacheService::Stub::experimental_async::UpdateCache(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::specrl::UpdateCacheResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UpdateCache_, context, request, response, std::move(f));
}

void RolloutCacheService::Stub::experimental_async::UpdateCache(::grpc::ClientContext* context, const ::specrl::UpdateCacheRequest* request, ::specrl::UpdateCacheResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_UpdateCache_, context, request, response, reactor);
}

void RolloutCacheService::Stub::experimental_async::UpdateCache(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::specrl::UpdateCacheResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_UpdateCache_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::specrl::UpdateCacheResponse>* RolloutCacheService::Stub::AsyncUpdateCacheRaw(::grpc::ClientContext* context, const ::specrl::UpdateCacheRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::specrl::UpdateCacheResponse>::Create(channel_.get(), cq, rpcmethod_UpdateCache_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::specrl::UpdateCacheResponse>* RolloutCacheService::Stub::PrepareAsyncUpdateCacheRaw(::grpc::ClientContext* context, const ::specrl::UpdateCacheRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::specrl::UpdateCacheResponse>::Create(channel_.get(), cq, rpcmethod_UpdateCache_, context, request, false);
}

RolloutCacheService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RolloutCacheService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RolloutCacheService::Service, ::specrl::UpdateCacheRequest, ::specrl::UpdateCacheResponse>(
          [](RolloutCacheService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::specrl::UpdateCacheRequest* req,
             ::specrl::UpdateCacheResponse* resp) {
               return service->UpdateCache(ctx, req, resp);
             }, this)));
}

RolloutCacheService::Service::~Service() {
}

::grpc::Status RolloutCacheService::Service::UpdateCache(::grpc::ServerContext* context, const ::specrl::UpdateCacheRequest* request, ::specrl::UpdateCacheResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace specrl

