// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rollout-cache.proto
// Original file comments:
// Copyright 2025 Bytedance Ltd. and/or its affiliates
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Protocol definition for rollout cache service
#ifndef GRPC_rollout_2dcache_2eproto__INCLUDED
#define GRPC_rollout_2dcache_2eproto__INCLUDED

#include "rollout-cache.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace specrl {

// The rollout cache service definition
class RolloutCacheService final {
 public:
  static constexpr char const* service_full_name() {
    return "specrl.RolloutCacheService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // RPC to update the cache with prompt hash and responses
    virtual ::grpc::Status UpdateCache(::grpc::ClientContext* context, const ::specrl::UpdateCacheRequest& request, ::specrl::UpdateCacheResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::specrl::UpdateCacheResponse>> AsyncUpdateCache(::grpc::ClientContext* context, const ::specrl::UpdateCacheRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::specrl::UpdateCacheResponse>>(AsyncUpdateCacheRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::specrl::UpdateCacheResponse>> PrepareAsyncUpdateCache(::grpc::ClientContext* context, const ::specrl::UpdateCacheRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::specrl::UpdateCacheResponse>>(PrepareAsyncUpdateCacheRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // RPC to update the cache with prompt hash and responses
      virtual void UpdateCache(::grpc::ClientContext* context, const ::specrl::UpdateCacheRequest* request, ::specrl::UpdateCacheResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UpdateCache(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::specrl::UpdateCacheResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void UpdateCache(::grpc::ClientContext* context, const ::specrl::UpdateCacheRequest* request, ::specrl::UpdateCacheResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void UpdateCache(::grpc::ClientContext* context, const ::specrl::UpdateCacheRequest* request, ::specrl::UpdateCacheResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void UpdateCache(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::specrl::UpdateCacheResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void UpdateCache(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::specrl::UpdateCacheResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::specrl::UpdateCacheResponse>* AsyncUpdateCacheRaw(::grpc::ClientContext* context, const ::specrl::UpdateCacheRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::specrl::UpdateCacheResponse>* PrepareAsyncUpdateCacheRaw(::grpc::ClientContext* context, const ::specrl::UpdateCacheRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status UpdateCache(::grpc::ClientContext* context, const ::specrl::UpdateCacheRequest& request, ::specrl::UpdateCacheResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::specrl::UpdateCacheResponse>> AsyncUpdateCache(::grpc::ClientContext* context, const ::specrl::UpdateCacheRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::specrl::UpdateCacheResponse>>(AsyncUpdateCacheRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::specrl::UpdateCacheResponse>> PrepareAsyncUpdateCache(::grpc::ClientContext* context, const ::specrl::UpdateCacheRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::specrl::UpdateCacheResponse>>(PrepareAsyncUpdateCacheRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void UpdateCache(::grpc::ClientContext* context, const ::specrl::UpdateCacheRequest* request, ::specrl::UpdateCacheResponse* response, std::function<void(::grpc::Status)>) override;
      void UpdateCache(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::specrl::UpdateCacheResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void UpdateCache(::grpc::ClientContext* context, const ::specrl::UpdateCacheRequest* request, ::specrl::UpdateCacheResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void UpdateCache(::grpc::ClientContext* context, const ::specrl::UpdateCacheRequest* request, ::specrl::UpdateCacheResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void UpdateCache(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::specrl::UpdateCacheResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void UpdateCache(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::specrl::UpdateCacheResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::specrl::UpdateCacheResponse>* AsyncUpdateCacheRaw(::grpc::ClientContext* context, const ::specrl::UpdateCacheRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::specrl::UpdateCacheResponse>* PrepareAsyncUpdateCacheRaw(::grpc::ClientContext* context, const ::specrl::UpdateCacheRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateCache_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // RPC to update the cache with prompt hash and responses
    virtual ::grpc::Status UpdateCache(::grpc::ServerContext* context, const ::specrl::UpdateCacheRequest* request, ::specrl::UpdateCacheResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateCache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UpdateCache() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_UpdateCache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateCache(::grpc::ServerContext* /*context*/, const ::specrl::UpdateCacheRequest* /*request*/, ::specrl::UpdateCacheResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateCache(::grpc::ServerContext* context, ::specrl::UpdateCacheRequest* request, ::grpc::ServerAsyncResponseWriter< ::specrl::UpdateCacheResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_UpdateCache<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_UpdateCache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_UpdateCache() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::specrl::UpdateCacheRequest, ::specrl::UpdateCacheResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::specrl::UpdateCacheRequest* request, ::specrl::UpdateCacheResponse* response) { return this->UpdateCache(context, request, response); }));}
    void SetMessageAllocatorFor_UpdateCache(
        ::grpc::experimental::MessageAllocator< ::specrl::UpdateCacheRequest, ::specrl::UpdateCacheResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::specrl::UpdateCacheRequest, ::specrl::UpdateCacheResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_UpdateCache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateCache(::grpc::ServerContext* /*context*/, const ::specrl::UpdateCacheRequest* /*request*/, ::specrl::UpdateCacheResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* UpdateCache(
      ::grpc::CallbackServerContext* /*context*/, const ::specrl::UpdateCacheRequest* /*request*/, ::specrl::UpdateCacheResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* UpdateCache(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::specrl::UpdateCacheRequest* /*request*/, ::specrl::UpdateCacheResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_UpdateCache<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_UpdateCache<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_UpdateCache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UpdateCache() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_UpdateCache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateCache(::grpc::ServerContext* /*context*/, const ::specrl::UpdateCacheRequest* /*request*/, ::specrl::UpdateCacheResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdateCache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UpdateCache() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_UpdateCache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateCache(::grpc::ServerContext* /*context*/, const ::specrl::UpdateCacheRequest* /*request*/, ::specrl::UpdateCacheResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateCache(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_UpdateCache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_UpdateCache() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UpdateCache(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_UpdateCache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateCache(::grpc::ServerContext* /*context*/, const ::specrl::UpdateCacheRequest* /*request*/, ::specrl::UpdateCacheResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* UpdateCache(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* UpdateCache(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateCache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UpdateCache() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::specrl::UpdateCacheRequest, ::specrl::UpdateCacheResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::specrl::UpdateCacheRequest, ::specrl::UpdateCacheResponse>* streamer) {
                       return this->StreamedUpdateCache(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UpdateCache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateCache(::grpc::ServerContext* /*context*/, const ::specrl::UpdateCacheRequest* /*request*/, ::specrl::UpdateCacheResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateCache(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::specrl::UpdateCacheRequest,::specrl::UpdateCacheResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_UpdateCache<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_UpdateCache<Service > StreamedService;
};

}  // namespace specrl


#endif  // GRPC_rollout_2dcache_2eproto__INCLUDED
